site_name: Benni's Blog
site_url: https://bboortz.github.io/
site_description: benni's blog
site_author: Benjamin Boortz
copyright: Benjamin Boortz <bennis.blog@secure.mailbox.org>
repo_url: https://github.com/bboortz/blog/
theme: cyborg
pages:
  - Home: index.md
  - Blog:
    - 2018-05-27 - How-to build a simple blog site: blog/2018_05_27_How-to-build-a-simple-blog-site.md
    - 2018-06-03 - How-to deploy mkdocs site to github pages: blog/2018_06_03_How-to-deploy-mkdocs-site-to-github-pages.md
    - 2018-06-10 - My first tries with Rust programming language: blog/2018_06_10_My_first_tries_with_Rust_programming_language.md
  - Links: links.md
  - About: about.md
